-- It must contain
-- (1) the delete/update statements used to change the tables (as in section 5), and
-- (2) the queries made (as in section 6), and
--(3) the statements used to create and apply functions, procedures, triggers, and events (as in section 7)
